services:
  redis-s2:
    image: redis:7
    container_name: redis-s2
    ports:
      - "6380:6379"
    volumes:
      - ./s2-data:/data
    command: redis-server --appendonly yes --replicaof 172.30.0.11 6379
    networks:
      redisnet:
        ipv4_address: 172.30.0.12

  sentinel-s2:
    image: redis:7
    container_name: sentinel-s2
    ports:
      - "26380:26379"
    volumes:
      - ./s2:/etc/redis  # Mount the entire directory to ensure Sentinel can write to it
    command: redis-server /etc/redis/sentinel.conf --sentinel
    networks:
      redisnet:
        ipv4_address: 172.30.0.22

networks:
  redisnet:
    name: redisnet
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
